version: "3.7"

services:
  caddy:
    image: caddy:2.4.6-alpine
    container_name: caddy
    restart: always
    volumes:
      - ./wwwroot:/usr/share/caddy
      - ./ssl:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
      - ./caddy/caddy.json:/etc/caddy/caddy.json
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./log/caddy:/var/log
    ports:
      - "80:80"
    networks:
      - free-net
    command: caddy run --config=/etc/caddy/caddy.json
  trojan:
    image: teddysun/trojan-go:0.10.6
    container_name: trojan
    restart: always
    volumes:
      - ./trojan/config:/etc/trojan-go
      - ./ssl:/ssl
    ports:
      - "443:443"
    depends_on:
      - caddy
    networks:
      - free-net
  v2:
    container_name: v2
    image: v2fly/v2fly-core:v4.44.0
    restart: always
    volumes:
      - ./v2configs:/etc/v2ray/conf
      - ./log/v2ray:/var/log
    command: v2ray -confdir /etc/v2ray/conf
    depends_on:
      - caddy
    networks:
      - free-net

networks:
  free-net:
    name: free-net
